FROM hypriot/rpi-alpine-scratch

RUN apk add --no-cache mosquitto

RUN mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log && \
    chown -R mosquitto:mosquitto /mosquitto && \
    touch /mosquitto/config/pwfile

COPY mosquitto.conf /mosquitto/config

RUN /usr/sbin/mosquitto_passwd -b /mosquitto/config/pwfile ${MQTT_USERNAME} ${MQTT_PASSWORD}

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]